name: publish

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm clean-install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Lint code
        run: npm run lint:check
      
  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: npm-publish
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm clean-install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build packages
        run: npm run build

      - name: Publish protocol-kit to npm
        run: npm publish
        working-directory: packages/protocol-kit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish relay-kit to npm
        run: npm publish
        working-directory: packages/relay-kit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}